server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
#   security:
#     user:
#       name: admin
#       password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.boot.entity
  configuration:
    map-underscore-to-camel-case: true 

# 添加日志配置，查看更多信息
logging:
  level:
    org.springframework.security: DEBUG
    com.atguigu.boot: DEBUG
    org.springframework.web: INFO

